// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ModelBuilderML.Model
{
    public class ModelInput
    {
        [ColumnName("duration"), LoadColumn(0)]
        public float Duration { get; set; }


        [ColumnName("protocol_type"), LoadColumn(1)]
        public float Protocol_type { get; set; }


        [ColumnName("service"), LoadColumn(2)]
        public float Service { get; set; }


        [ColumnName("flag"), LoadColumn(3)]
        public float Flag { get; set; }


        [ColumnName("src_bytes"), LoadColumn(4)]
        public float Src_bytes { get; set; }


        [ColumnName("dst_bytes"), LoadColumn(5)]
        public float Dst_bytes { get; set; }


        [ColumnName("land"), LoadColumn(6)]
        public float Land { get; set; }


        [ColumnName("wrong_fragment"), LoadColumn(7)]
        public float Wrong_fragment { get; set; }


        [ColumnName("urgent"), LoadColumn(8)]
        public float Urgent { get; set; }


        [ColumnName("hot"), LoadColumn(9)]
        public float Hot { get; set; }


        [ColumnName("num_failed_logins"), LoadColumn(10)]
        public float Num_failed_logins { get; set; }


        [ColumnName("logged_in"), LoadColumn(11)]
        public float Logged_in { get; set; }


        [ColumnName("num_compromised"), LoadColumn(12)]
        public float Num_compromised { get; set; }


        [ColumnName("root_shell"), LoadColumn(13)]
        public float Root_shell { get; set; }


        [ColumnName("su_attempted"), LoadColumn(14)]
        public float Su_attempted { get; set; }


        [ColumnName("num_root"), LoadColumn(15)]
        public float Num_root { get; set; }


        [ColumnName("num_file_creations"), LoadColumn(16)]
        public float Num_file_creations { get; set; }


        [ColumnName("num_shells"), LoadColumn(17)]
        public float Num_shells { get; set; }


        [ColumnName("num_access_files"), LoadColumn(18)]
        public float Num_access_files { get; set; }


        [ColumnName("num_outbound_cmds"), LoadColumn(19)]
        public float Num_outbound_cmds { get; set; }


        [ColumnName("is_host_login"), LoadColumn(20)]
        public float Is_host_login { get; set; }


        [ColumnName("is_guest_login"), LoadColumn(21)]
        public float Is_guest_login { get; set; }


        [ColumnName("count"), LoadColumn(22)]
        public float Count { get; set; }


        [ColumnName("srv_count"), LoadColumn(23)]
        public float Srv_count { get; set; }


        [ColumnName("serror_rate"), LoadColumn(24)]
        public float Serror_rate { get; set; }


        [ColumnName("srv_serror_rate"), LoadColumn(25)]
        public float Srv_serror_rate { get; set; }


        [ColumnName("rerror_rate"), LoadColumn(26)]
        public float Rerror_rate { get; set; }


        [ColumnName("srv_rerror_rate"), LoadColumn(27)]
        public float Srv_rerror_rate { get; set; }


        [ColumnName("same_srv_rate"), LoadColumn(28)]
        public float Same_srv_rate { get; set; }


        [ColumnName("diff_srv_rate"), LoadColumn(29)]
        public float Diff_srv_rate { get; set; }


        [ColumnName("srv_diff_host_rate"), LoadColumn(30)]
        public float Srv_diff_host_rate { get; set; }


        [ColumnName("dst_host_count"), LoadColumn(31)]
        public float Dst_host_count { get; set; }


        [ColumnName("dst_host_srv_count"), LoadColumn(32)]
        public float Dst_host_srv_count { get; set; }


        [ColumnName("dst_host_same_srv_rate"), LoadColumn(33)]
        public float Dst_host_same_srv_rate { get; set; }


        [ColumnName("dst_host_diff_srv_rate"), LoadColumn(34)]
        public float Dst_host_diff_srv_rate { get; set; }


        [ColumnName("dst_host_same_src_port_rate"), LoadColumn(35)]
        public float Dst_host_same_src_port_rate { get; set; }


        [ColumnName("dst_host_srv_diff_host_rate"), LoadColumn(36)]
        public float Dst_host_srv_diff_host_rate { get; set; }


        [ColumnName("dst_host_serror_rate"), LoadColumn(37)]
        public float Dst_host_serror_rate { get; set; }


        [ColumnName("dst_host_srv_serror_rate"), LoadColumn(38)]
        public float Dst_host_srv_serror_rate { get; set; }


        [ColumnName("dst_host_rerror_rate"), LoadColumn(39)]
        public float Dst_host_rerror_rate { get; set; }


        [ColumnName("dst_host_srv_rerror_rate"), LoadColumn(40)]
        public float Dst_host_srv_rerror_rate { get; set; }


        [ColumnName("attackName"), LoadColumn(41)]
        public string AttackName { get; set; }


        [ColumnName("someInt"), LoadColumn(42)]
        public float SomeInt { get; set; }


    }
}
